Repository Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded, pull requests merged in 2020-12, with the labels that each got.

#126 Enabled the exact copy spawn in the Mob Duplicator
  config/industrialforegoing.cfg
Labels: enhancement

#124 Fix: Using any Laser metadata to craft the Quarry
  scripts/expert/ExtraUtilites2.zs
Labels: bug

#121 fix yellorium unification
  scripts/expert/Oredict.zs
  scripts/normal/Oredict.zs
Labels: bug

#122 Recipe fix
  scripts/expert/Creative.zs
  scripts/normal/Creative.zs
Labels: bug

#123 fix Bronze Item Casing now uses Bronze instead of Brass
  config/ic2/metal_former_rolling.ini
Labels: bug

#127 Added Tooltips for Firm Tofu and Silken Tofu
  scripts/expert/PamsHarvestCraft.zs
  scripts/normal/PamsHarvestCraft.zs
Labels: enhancement

#131 tweak FoamFix config for reducing RAM
  config/foamfix.cfg
Labels: enhancement

#130 Recipes fixes
  config/energyconverters.cfg
  config/phosphor.json
  config/plethora-core.cfg
  config/plethora.cfg
  scripts/normal/Avaritia.zs
Labels: bug

#132 Ai improvements activation
  config/bbm/AI_Improvements.cfg
Labels: enhancement

#133 Fixing the JEI Search Crash in FoamFix
  config/foamfix.cfg
Labels: bug

#134 Fixing Resonant Conversion Kit, added the default Deep Dark Portale Recipe for both Modes and Removed the Void Metal Ingot Recipe from Arc Furnace
  scripts/expert/ExtraUtilites2.zs
  scripts/expert/Thaumcraft.zs
  scripts/expert/ThermalExpansion.zs
  scripts/normal/ExtraUtilities2.zs
Labels: bug, enhancement

#129 Added all Assembly Table Recipes to Draconic Fusion for an alternative
  scripts/expert/DraconicEvolution.zs
Labels: enhancement
